export type ContentIdea = { id: string; category: string; title: string; query: string; workflow: "stock-reel" | "business" | "general" | "children-story" };
const collections: Array<{ category: string; workflow: ContentIdea["workflow"]; ideas: Array<[string, string]> }> = [
  { category: "Nature & wildlife", workflow: "stock-reel", ideas: [["A quiet minute beside a waterfall", "forest waterfall"], ["Waves arriving one after another", "ocean waves beach"], ["Birds building their home", "bird nest"], ["Morning light through the forest", "forest sunlight"], ["A butterfly in the garden", "butterfly flower"]] },
  { category: "Places & travel", workflow: "stock-reel", ideas: [["A city waking up", "city sunrise"], ["A peaceful mountain trail", "mountain hiking trail"], ["Rainy evening streets", "rain city street"], ["A train journey through the countryside", "train countryside"]] },
  { category: "Food & craft", workflow: "stock-reel", ideas: [["Bread taking shape by hand", "kneading bread dough"], ["A potter shaping clay", "pottery wheel hands"], ["Coffee being prepared carefully", "pour over coffee"], ["A pencil sketch coming to life", "drawing pencil sketch"], ["Fresh ingredients at the market", "vegetable market"]] },
  { category: "Animals & everyday moments", workflow: "stock-reel", ideas: [["A cat enjoying a sunny window", "cat window"], ["A dog exploring the park", "dog park"], ["Horses grazing in a field", "horses field"], ["Small details in a busy garden", "garden insects"]] },
  { category: "Small business", workflow: "business", ideas: [["Show a customer the next step instead of saying wait", "shop assistant customer"], ["How a repair shop explains a delay clearly", "repair shop customer"], ["A bakery prepares for its morning rush", "bakery preparing bread"], ["Make a useful customer follow-up specific", "customer service phone"]] },
  { category: "Work & practical skills", workflow: "business", ideas: [["Turn a vague task into one visible next step", "writing task notebook"], ["Prepare a short meeting around one decision", "team meeting notebook"], ["Show your work with a simple before-and-after", "craft workshop work"], ["A handover note that someone can actually use", "writing notes desk"]] },
  { category: "Everyday learning", workflow: "general", ideas: [["Practice one small drawing skill at a time", "pencil drawing hands"], ["Use a real example to remember a new word", "reading notebook"], ["Watch how shadows change through the day", "sunlight shadows"], ["Notice patterns in leaves", "leaves close up"]] },
  { category: "Home & hobbies", workflow: "general", ideas: [["Create a small place for frequently used tools", "organizing tools"], ["Start a windowsill herb garden", "herbs windowsill"], ["Repair a loose button instead of discarding a shirt", "sewing button hands"], ["A simple way to sort a cluttered desk", "organizing desk"]] },
  { category: "Movement & outdoors", workflow: "stock-reel", ideas: [["A calm walk through the park", "walking park"], ["A bicycle ride beside the water", "cycling waterfront"], ["A climber working through a route", "indoor rock climbing"], ["Skateboard practice and persistence", "skateboard practice"]] },
  { category: "Children's original stories", workflow: "children-story", ideas: [["Benny Bunny and Tika Bird take turns with a garden ball", "bunny bird ball"], ["A bear and a fox tidy their playroom together", "bear fox toys"], ["A puppy and kitten help a little star glow", "puppy kitten star"], ["Two forest friends untangle a kite patiently", "forest friends kite"]] },
];
export const CONTENT_IDEAS: ContentIdea[] = Array.from({ length: Math.max(...collections.map(group => group.ideas.length)) }, (_, index) => collections.flatMap(({ category, workflow, ideas }, group) => ideas[index] ? [{ id: `${group}-${index}`, category, workflow, title: ideas[index][0], query: ideas[index][1] }] : [])).flat();

export function contentIdeas(history: string[], category = "all", rotation = 0) {
  const seen = new Set(history.map(title => title.toLowerCase()));
  const candidates = CONTENT_IDEAS.filter(idea => category === "all" || idea.category === category);
  return [...candidates.slice(rotation % Math.max(1, candidates.length)), ...candidates.slice(0, rotation % Math.max(1, candidates.length))]
    .sort((a, b) => Number(seen.has(a.title.toLowerCase())) - Number(seen.has(b.title.toLowerCase())));
}
