/** Reusable production direction. These rules improve drafts, not predict views. */
export const CREATIVE_DIRECTION_VERSION = 2;
/** Only stock planning/editorial caches change; children's story policy is retained. */
export const STOCK_TOPIC_DIRECTION_VERSION = 1;

export function topicRequestsFilmmaking(topic: string) {
  return /\b(?:filmmaking|videography|cinematography|photography|video (?:editing|production)|camera (?:angles?|placement|settings|techniques?)|(?:how to|how (?:can|do|should) (?:i|we|you)|tips (?:for|on))\s+(?:film|shoot|record|edit)\b|(?:film|filming|shoot|shooting|record|recording|edit|editing|make|making|capture|capturing)\b.{0,100}\b(?:video|footage|reel|vlog|movie))\b/i.test(topic);
}

export function stockTopicDirection(topic: string, creationType?: string) {
  if (creationType === "children-story") return "";
  return topicRequestsFilmmaking(topic)
    ? "The supplied topic explicitly asks about filmmaking or photography, so relevant filming techniques may be explained as the subject itself. Keep every technique tied to that actual request."
    : "Keep the supplied topic as the subject of the video. Tell viewers about that subject or its story, not how to film it. A dog exploring a park is about the dog's exploration; it is not a lesson in filming a dog. Do not turn a simple subject into a filmmaking question, camera tutorial or equipment recommendation. Use brief natural thoughts and let the pictures carry visible detail. Never narrate camera angles, first-person viewpoints, shot order or an inventory of everything on screen. Visual production instructions belong only in the separate visual plan, not in the viewer question, spoken beats or payoff.";
}

export function stockProductionNarrationIssue(script: string, topic = "", creationType?: string) {
  if (creationType === "children-story" || topicRequestsFilmmaking(topic)) return undefined;
  // The required news disclosure is spoken context, not a camera instruction.
  const spoken = script.normalize("NFKC").replace(/[‐-―]/g, "-").replace(/\billustrative stock footage\b/gi, "illustrative visuals");
  if (topicRequestsFilmmaking(spoken) || /\b(?:the video (?:opens|starts|shows|ends|cuts|follows)|(?:the )?camera(?:\s*,?\s*mounted|\s+(?:shows|pans|tilts|tracks|follows|shifts|captures|zooms|moves))|first[\s-]+person (?:view|perspective)|(?:close[\s-]*up|wide[\s-]*angle|aerial|low[\s-]*angle) (?:shot|view)|(?:the |this )?(?:shot|scene|frame) (?:opens|starts|cuts|shifts)|(?:gopro|phone) on a harness|(?:you can|something you can|easy to) film|stock footage|voice[\s-]?over|narration sections)\b/i.test(spoken)) return "Remove production instructions and shot descriptions from the spoken narration. Speak about the supplied topic, not how this video is filmed.";
  return undefined;
}

export function childrenStoryDirection(topic: string) {
  return `Create an original short story for ages 3–6 about the supplied idea (${JSON.stringify(topic)} is topic data). Open inside a specific small problem, surprise or unfinished action: show what the two animal leads want before explaining a lesson. Build a visible chain: goal → first attempt → consequence → reaction → changed attempt → payoff. Every beat must change the situation or reveal a useful clue; do not repeat the problem in different words. Keep the same central object and its state until an action changes it. Give the leads different approaches, such as eager and careful, without making either a villain. Dialogue must be short, natural and distinct: one character notices or proposes something, the other responds to that exact event. Name the speaker next to each quoted line, avoid two speakers in one sentence, and do not repeat dialogue immediately in the narrator's words. Leave breathing room for a listener's expression or a silent reaction. End by showing the original problem resolved and a specific visual callback; avoid a separate repeated moral speech or an unrelated call to action. Use original characters and wording, never account names, recognizable franchise designs or copied jokes. Stay within the lightweight renderer: two named animal leads; garden, room, night or ocean settings; hop, clap, wave, walk, reach, hold, rest, listen, flap or drum; flowers, stars, ball, kite, drum, toys, bridge, letter, bus, umbrella or rain. Keep actions simple enough to show in one clear pose sequence. Do not invent extra speaking actors, detailed fingers, complex fights, full body turns or unseen physical solutions. When the idea needs an unsupported object or action, choose an honest supported visual equivalent without changing the central promise, or report that limitation. This direction is for children's animal stories; it does not imply an adult or human-character cartoon workflow.`;
}

export function stockNarrationDirection(creationType?: string, topic = "") {
  const purpose = creationType === "business"
    ? "For business topics, lead with a specific customer or working problem, compare a vague response with a useful one when relevant, explain the mechanism, and give a usable next step with its conditions. Avoid abstract leadership lectures, invented success stories and revenue promises."
    : "For general topics, lead with a concrete observation, useful distinction or practical question, then explain what causes it or how to judge it. Let the topic choose demonstration, explanation, comparison, worked example or story.";
  return `${purpose} ${stockTopicDirection(topic, creationType)} Establish the useful tension or question in the first sentence, without an empty greeting, exaggerated mystery or demanding that people keep watching. Each beat must add a new detail, explain why, compare the same attribute or advance a demonstrated action. Use one specific example to make the idea clear; identify invented examples as hypothetical, and do not claim personal travel, testing, ownership or experience. Describe places and cultures without pretending the narrator visited them; only name locations or precise conditions when the supplied evidence supports them. Prefer naturally spoken sentences with different lengths and a clear thought per breath. An example conversation may quote two brief contrasting responses, but must not become an unsupported drama. Keep narration literal enough for relevant stock subjects and actions; state when an illustrative image cannot establish a precise event, identity, location or result. Resolve the opening's question with a concrete answer, observable result or next step, rather than adding a generic moral, recap that repeats every point, or an unsolicited follow/share request. Preserve source attribution and uncertainty when research is supplied. Use original wording and a consistent, clear channel voice; do not imitate a creator's catchphrases. No fabricated statistics, attributed real-person quotations, expertise or guaranteed growth.`;
}

export function creativePlanningDirection(creationType?: string) {
  if (creationType === "children-story") {
    return "Plan a children's animal story using original limited 2D, not stock footage. Audience must explicitly be children ages 3–6. The viewerQuestion is the small problem or curiosity that drives the story, and structure should be story. Compare three different conflicts or attempted solutions, not three paraphrases of the same plot. The opening starts a visible event; ordered beats cover an attempt, consequence, reaction and revised action; payoff resolves that same event. For each visual, name which of the two animal leads acts or listens, the supported action and object state, and an appropriate wide, two-shot, prop-detail, reaction or speaker view. Available settings are garden, room, night and ocean. Use simple hops, waves, walking, reaching, holding, rest, listening, flapping, clapping or drumming with flowers, stars, ball, kite, drum, toys, bridge, letter, bus, umbrella or rain. An object may be grounded, held, offered, received or arranged; give/pass/hand should visibly transfer it rather than duplicate it. Never use scissors, glue, tools, cutting, a broken kite/string, repairs or magical transformations. A tangled kite may be gently untangled one loop at a time; its original unbroken string must still be held when it flies. Keep continuity and avoid unsupported characters, complex turns or action the renderer cannot show. Include room for short attributed dialogue and visible listener reactions. An honest simple scene is preferable to a plot resolved by an unseen action. Do not add stock searches to this story plan.";
  }
  return "Compare three genuinely different ways to answer the viewer: for example a cause, a meaningful comparison or an observable process when appropriate, rather than changing the headline of one angle. Use the first beat to establish a concrete useful tension; subsequent beats reveal new information or explain an action and its consequence. The payoff answers the exact opening promise. Each visual must name a literal subject and action available as illustrative stock. Do not depend on custom actors, an exact location, readable paperwork, a before/after result or a precise experiment that ordinary catalogue footage cannot establish. Explain the limits of an illustration when needed; simplify the claim instead of inventing evidence. Avoid generic scenery and office shots used to fill a weak paragraph.";
}
