import fs from "node:fs/promises"; import os from "node:os"; import path from "node:path";
import { db } from "./db"; import { decryptSecret } from "./secrets"; import { getPresignedReadUrl } from "./s3"; import { publishToPlatform } from "./publisher";

export async function processScheduledPublishes(limit=5){
  const jobs=await db.publishHistory.findMany({where:{status:"SCHEDULED",scheduledFor:{lte:new Date()}},include:{project:{include:{user:{include:{publishSettings:true}}}}},orderBy:{scheduledFor:"asc"},take:limit});
  for(const job of jobs){let temp:string|null=null;try{const settings=job.project.user.publishSettings;if(!settings)throw new Error("Publishing connection is missing");await db.publishHistory.update({where:{id:job.id},data:{status:"PENDING",processingStage:"UPLOADING",attemptCount:{increment:1}}});const publicUrl=await getPresignedReadUrl(job.mediaPath!,7200);let mediaPath=job.mediaPath!;if(job.platform==="YouTube"){temp=path.join(os.tmpdir(),`${job.id}.mp4`);const res=await fetch(publicUrl);if(!res.ok)throw new Error("Scheduled media is unavailable");await fs.writeFile(temp,Buffer.from(await res.arrayBuffer()));mediaPath=temp;}const result=await publishToPlatform({projectId:job.projectId,clipId:job.clipId,clipTitle:job.clipTitle,platform:job.platform,caption:job.caption||undefined,hashtags:job.hashtags||undefined,youtubeTitle:job.youtubeTitle||undefined,youtubeDesc:job.youtubeDesc||undefined,youtubeTags:job.youtubeTags||undefined},mediaPath,{userId:job.project.userId,instagramAccessToken:decryptSecret(settings.instagramAccessToken),instagramAccountId:settings.instagramAccountId,youtubeAccessToken:decryptSecret(settings.youtubeAccessToken),youtubeRefreshToken:decryptSecret(settings.youtubeRefreshToken),youtubeClientId:process.env.GOOGLE_CLIENT_ID,youtubeClientSecret:process.env.GOOGLE_CLIENT_SECRET},publicUrl);await db.publishHistory.update({where:{id:job.id},data:result.success?{status:"PUBLISHED",processingStage:"PUBLISHED",postUrl:result.postUrl,publishedAt:new Date(),error:null}:{status:"FAILED",processingStage:"FAILED",error:result.error}});}catch(error){await db.publishHistory.update({where:{id:job.id},data:{status:"FAILED",processingStage:"FAILED",error:error instanceof Error?error.message:"Scheduled publish failed"}});}finally{if(temp)await fs.unlink(temp).catch(()=>undefined);}}
  return jobs.length;
}

export function startScheduler(){console.log("AuraClip: scheduled publishing is handled by the authenticated cron endpoint.");}
