"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { FeedbackDecision, FeedbackDimension, QualityAssessment, QualityManagerState } from "@/lib/managerTypes";

const field="mt-1 w-full rounded-lg border border-[#bfcaa6] bg-white p-2 text-sm";
const button="rounded-lg bg-[#394a2a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
const labels:Record<QualityAssessment['decision'],string>={BLOCKED:"Needs a fix",REVISE:"Revise before posting",AWAITING_REVIEW:"Waiting for your review",OWNER_APPROVED:"Approved by you"};
export default function QualityManager({initialReviewId}:{initialReviewId?:string}) {
  const [data,setData]=useState<QualityManagerState|null>(null),[selected,setSelected]=useState(initialReviewId||""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setBusy(true);try{const response=await fetch('/api/manager/status',{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error);setData(value);setError("");}catch(e){setError(e instanceof Error?e.message:"Manager unavailable.");}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const assessment=data?.assessments.find(item=>item.reviewId===selected)||data?.assessments[0];
  return <main className="min-h-screen bg-[#f4f0e7] px-5 py-8 text-[#1e2719]"><div className="mx-auto max-w-5xl">
    <Link href="/dashboard" className="text-sm font-semibold underline">← Back to studio</Link>
    <h1 className="mt-6 text-3xl font-semibold">Content quality manager</h1>
    <p className="mt-3 max-w-3xl text-sm leading-6">A finished render is not automatically good content. Watch and listen, record what needs fixing, and let Phoenix use that feedback in later children’s stories. No paid service or automatic posting.</p>
    <button className={`${button} mt-4`} disabled={busy} onClick={()=>void load()}>{busy?'Checking…':'Refresh quality checks'}</button>
    {error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}
    {data&&<>
      <section className="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-semibold">Current limits—not hidden behind a score</h2><p className="mt-2 text-sm">Automatic singing is not installed. Song videos require your sung recording plus lyrics. Uploaded audio is not automatically proof of good singing.</p><p className="mt-2 text-sm">{data.capabilities.animation}. This is simple character animation, not Baby Shark-level production. Higher resolution alone will not fix acting or art quality.</p></section>
      <section className="mt-5 rounded-xl bg-[#fffdf7] p-5"><h2 className="font-semibold">What the manager has learned</h2><p className="mt-2 text-sm">{data.guidance.feedbackCount} reviewed files · {data.queued} queued · {data.running} running · {data.failed} failed jobs</p><p className="mt-2 text-xs leading-5 text-[#687657]">{data.capabilities.learning} Only structured ratings change these rules; notes remain your review record. Changes apply to newly planned work, not existing exports.</p>{data.guidance.rules.length?<ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{data.guidance.rules.map(rule=><li key={rule}>{rule}</li>)}</ul>:<p className="mt-3 text-sm">No weak areas recorded yet. Rate a video below—Phoenix must not invent feedback on your behalf.</p>}<p className="mt-3 text-xs text-[#687657]">Rule revision: {data.guidance.revision}. Each new children’s export records the rules used.</p></section>
      <section className="mt-5 rounded-xl bg-[#fffdf7] p-5"><label className="text-sm font-semibold">Video to review<select className={field} value={assessment?.reviewId||""} onChange={event=>setSelected(event.target.value)}>{data.assessments.map(item=><option key={item.reviewId} value={item.reviewId}>{item.title}</option>)}</select></label>
      {assessment?<div className="mt-5"><h2 className="text-xl font-semibold">{labels[assessment.decision]}</h2>{assessment.blockers.map(message=><p key={message} className="mt-2 rounded-lg bg-red-50 p-3 text-sm text-red-800">{message}</p>)}<ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{assessment.checks.map(check=><li key={check}>{check}</li>)}</ul>
        <div className="mt-4 flex gap-4 text-sm font-semibold"><Link className="underline" href={`/dashboard/edit/${assessment.reviewId}`}>Watch and edit video</Link><a className="underline" href={`/api/review-files/${assessment.reviewId}/media`} target="_blank" rel="noreferrer">Open finished MP4</a></div>
        <FeedbackForm key={assessment.reviewId} assessment={assessment} onSaved={load}/>
      </div>:<p className="mt-4 text-sm">Create a video first. Your review files will appear here.</p>}</section>
    </>}
  </div></main>;
}
function FeedbackForm({assessment,onSaved}:{assessment:QualityAssessment;onSaved:()=>Promise<void>}) {
  const [ratings,setRatings]=useState(assessment.feedback?.ratings||{story:3,visuals:3,audio:3,captions:3}),[decision,setDecision]=useState<FeedbackDecision>(assessment.feedback?.decision||'revise'),[note,setNote]=useState(assessment.feedback?.note||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setNotice('');try{const response=await fetch('/api/manager/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:assessment.reviewId,ratings,decision,note})});const data=await response.json();if(!response.ok)throw new Error(data.error);setNotice('Feedback saved locally. Future children’s briefs and caption grouping use the updated rules.');await onSaved();}catch(e){setNotice(e instanceof Error?e.message:'Could not save feedback.');}finally{setBusy(false);}}
  return <form onSubmit={save} className="mt-6 border-t border-[#d5ddb8] pt-5"><h3 className="font-semibold">Your review teaches the manager</h3><p className="mt-1 text-xs">1 = poor · 3 = acceptable draft · 5 = strong. Ratings of 1–2 create an improvement priority. Re-rating replaces this file’s previous feedback, without counting it twice.</p><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{(['story','visuals','audio','captions'] as FeedbackDimension[]).map(dimension=><label key={dimension} className="text-sm capitalize">{dimension}<select className={field} value={ratings[dimension]} onChange={event=>setRatings({...ratings,[dimension]:Number(event.target.value)})}>{[1,2,3,4,5].map(value=><option key={value} value={value}>{value}</option>)}</select></label>)}</div><label className="mt-4 block text-sm">Decision<select className={field} value={decision} onChange={event=>setDecision(event.target.value as FeedbackDecision)}><option value="revise">Revise before posting</option><option value="keep">Keep—personally reviewed</option></select></label><label className="mt-4 block text-sm">What specifically needs changing?<textarea className={field} rows={3} maxLength={1000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Example: the voice sounds rushed; the bear's action does not match the scene."/></label><button className={`${button} mt-4`} disabled={busy}>{busy?'Saving…':'Save review and update manager'}</button>{notice&&<p role="status" className="mt-3 text-sm">{notice}</p>}</form>;
}
