"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Brain, Captions, Loader2, Music2, ShieldCheck, type LucideIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import ChannelConnections from "@/components/ChannelConnections";

type Settings={aiTone?:string;aiInstructions?:string;subtitleFont?:string;subtitleColor?:string;subtitleSize?:string;subtitleUppercase?:boolean;subtitleStroke?:boolean;defaultMusicVolume?:number;duckingLevel?:number};
const defaults:Settings={aiTone:"balanced",aiInstructions:"",subtitleFont:"Montserrat",subtitleColor:"#FFFFFF",subtitleSize:"lg",subtitleUppercase:false,subtitleStroke:true,defaultMusicVolume:.15,duckingLevel:.8};
const sections=[{id:"channels",label:"Your channels",icon:ShieldCheck},{id:"ai",label:"AI clips",icon:Brain},{id:"captions",label:"Captions",icon:Captions},{id:"audio",label:"Audio",icon:Music2},{id:"system",label:"System",icon:ShieldCheck}];
export default function SettingsPage(){
 const[data,setData]=useState<Settings|null>(null);const[saving,setSaving]=useState(false);const[notice,setNotice]=useState("");const[usage,setUsage]=useState({bytes:0,percent:0});
 useEffect(()=>{try{const stored=window.localStorage.getItem("phoenix-studio-settings");setData(stored?{...defaults,...JSON.parse(stored)}:defaults)}catch{setData(defaults)}void fetch("/api/storage/usage",{cache:"no-store"}).then(async response=>{if(response.ok)setUsage(await response.json())}).catch(()=>undefined)},[]);
 function save(){if(!data)return;setSaving(true);try{window.localStorage.setItem("phoenix-studio-settings",JSON.stringify(data));setNotice("All preferences saved on this PC.")}catch{setNotice("Could not save preferences in this browser.")}setSaving(false)}
 if(!data)return <div className="grid min-h-screen place-items-center bg-[#101114]"><Loader2 className="h-5 w-5 animate-spin text-violet-400"/></div>;
 return <main className="min-h-screen bg-[#101114] px-5 py-8 text-[#f3f3f5]"><div className="mx-auto max-w-6xl"><Link href="/dashboard" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4"/>Back to studio</Link><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Settings</h1><p className="mt-2 text-sm text-slate-400">Local clip intelligence, captions, audio, and system preferences.</p></div><Button onClick={save} disabled={saving} className="mt-4 rounded-xl bg-violet-600 text-white hover:bg-violet-500 sm:mt-0">{saving?"Saving…":"Save all changes"}</Button></div>{notice&&<div className="mt-6 rounded-xl border border-white/10 bg-[#18191d] px-4 py-3 text-sm text-slate-200">{notice}</div>}
 <div className="mt-8 grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="h-fit rounded-2xl border border-white/10 bg-[#15161a] p-2 lg:sticky lg:top-5">{sections.map(({id,label,icon:Icon})=><a key={id} href={`#${id}`} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-slate-400 hover:bg-white/5 hover:text-white"><Icon className="h-4 w-4"/>{label}</a>)}</aside><div className="space-y-6">
 <ChannelConnections/>
 <Panel id="ai" icon={Brain} title="Free local AI preferences" copy="Phoenix uses the Ollama model installed on this PC. No Gemini, Kimi, or paid AI API is used."><div className="grid gap-5 sm:grid-cols-2"><Field label="Analysis model"><select value="ollama-qwen2.5:3b" disabled><option value="ollama-qwen2.5:3b">Ollama · qwen2.5:3b (local)</option></select></Field><Field label="Writing style"><select value={data.aiTone||"balanced"} onChange={e=>setData({...data,aiTone:e.target.value})}><option value="balanced">Balanced</option><option value="professional">Professional</option><option value="energetic">Energetic</option><option value="educational">Educational</option><option value="clickbait">High-energy hooks</option></select></Field></div><Field label="Custom instructions" hint="Used when selecting clips and generating titles, captions, and hooks locally."><textarea rows={4} maxLength={2000} value={data.aiInstructions||""} onChange={e=>setData({...data,aiInstructions:e.target.value})} placeholder="Example: Prefer clear educational moments. Avoid exaggerated claims."/></Field></Panel>
 <Panel id="captions" icon={Captions} title="Caption defaults" copy="New clips start with these subtitle settings."><div className="grid gap-5 sm:grid-cols-3"><Field label="Font"><select value={data.subtitleFont||"Montserrat"} onChange={e=>setData({...data,subtitleFont:e.target.value})}><option>Montserrat</option><option>Inter</option><option>Arial</option><option>Poppins</option><option>Roboto</option></select></Field><Field label="Size"><select value={data.subtitleSize||"lg"} onChange={e=>setData({...data,subtitleSize:e.target.value})}><option value="sm">Small</option><option value="md">Medium</option><option value="lg">Large</option><option value="xl">Extra large</option></select></Field><Field label="Color"><div className="flex h-11 items-center gap-3 rounded-xl border border-white/10 bg-[#111216] px-3"><input type="color" value={data.subtitleColor||"#FFFFFF"} onChange={e=>setData({...data,subtitleColor:e.target.value})} className="h-7 w-9 cursor-pointer border-0 bg-transparent"/><span className="text-sm text-slate-300">{data.subtitleColor||"#FFFFFF"}</span></div></Field></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Toggle label="Caption outline" copy="Improve readability over bright video." checked={Boolean(data.subtitleStroke)} onChange={value=>setData({...data,subtitleStroke:value})}/><Toggle label="Uppercase captions" copy="Use uppercase text for every spoken word." checked={Boolean(data.subtitleUppercase)} onChange={value=>setData({...data,subtitleUppercase:value})}/></div></Panel>
 <Panel id="audio" icon={Music2} title="Audio defaults" copy="Set the starting balance for voice and music."><div className="grid gap-6 sm:grid-cols-2"><Range label="Background music" copy="Default music level on new clips." value={data.defaultMusicVolume??.15} onChange={value=>setData({...data,defaultMusicVolume:value})}/><Range label="Voice ducking" copy="How much music lowers while someone speaks." value={data.duckingLevel??.8} onChange={value=>setData({...data,duckingLevel:value})}/></div></Panel>
 <Panel id="system" icon={ShieldCheck} title="Free local system" copy="Rendering and review storage stay on this PC."><div className="grid gap-3 sm:grid-cols-2"><Status label="AI cost" value="$0 · Ollama local" good/><Status label="Video renderer" value="FFmpeg local" good/><Status label="Local review files" value={`${(usage.bytes/1024**3).toFixed(2)} GB used`} good/><Status label="Posting" value="Review, then upload" good/></div></Panel>
 </div></div></div></main>;
}
function Panel({id,icon:Icon,title,copy,children}:{id:string;icon:LucideIcon;title:string;copy:string;children:React.ReactNode}){return <section id={id} className="scroll-mt-5 rounded-2xl border border-white/10 bg-[#18191d] p-6"><div className="mb-6 flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-violet-500/10 text-violet-400"><Icon className="h-5 w-5"/></span><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-400">{copy}</p></div></div>{children}</section>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}{hint&&<span className="ml-2 font-normal text-slate-500">{hint}</span>}<div className="mt-1.5 [&>select]:h-11 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-white/10 [&>select]:bg-[#111216] [&>select]:px-3 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-white/10 [&>textarea]:bg-[#111216] [&>textarea]:p-3 [&>textarea]:outline-none">{children}</div></label>}
function Toggle({label,copy,checked,onChange}:{label:string;copy:string;checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!checked)} className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-[#111216] p-4 text-left"><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-slate-500">{copy}</span></span><span className={`h-6 w-11 rounded-full p-1 transition ${checked?"bg-violet-600":"bg-white/10"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${checked?"translate-x-5":""}`}/></span></button>}
function Range({label,copy,value,onChange}:{label:string;copy:string;value:number;onChange:(v:number)=>void}){return <label><span className="flex justify-between text-sm font-medium"><span>{label}</span><span className="text-slate-400">{Math.round(value*100)}%</span></span><p className="mt-1 text-xs text-slate-500">{copy}</p><input type="range" min="0" max="1" step=".05" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-4 w-full accent-violet-500"/></label>}
function Status({label,value,good}:{label:string;value:string;good:boolean}){return <div className="flex items-center justify-between rounded-xl border border-white/10 bg-[#111216] p-4"><span className="text-sm text-slate-400">{label}</span><span className={`text-xs font-semibold ${good?"text-emerald-400":"text-amber-400"}`}>{value}</span></div>}
